spring:
  datasource:
    url: jdbc:postgresql://172.168.5.30:5432/coluy24
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    view-names: thymeleaf/*
  view:
    view-names: jsp/*
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.mail: DEBUG

app:
  base-url: "http://localhost:5874/"